### ISSUE TITLE
建议将库设置为模版

### ISSUE THREAD

**Issue by allenwoods** [Ruzim/NSFC-application-template-latex#3]
Yan老师您好，非常感谢制作并分享了这个模板！

一点小建议，在Github中可以将此库设置为模版（cc zo操作见下图），这样其他老师可以一键基于此库生成自己的repo，然后导入overleaf。这样的好处主要是可能有老师会希望将基于此库的申请书设为private时，可以直接用模板生成。如果是folk的方式，就必须设置成公开的。

![image](https://user-images.githubusercontent.com/7327215/217430257-d37b2ee5-9d10-49bd-9016-5b9e68cc1cd0.png)

**Comment by Ruzim** [comment]
好的，应该已经设置好了。我对github也不太熟，不知道有没有设对。

**Comment by allenwoods** [comment]
对的，现在已经可以使用啦

![image](https://user-images.githubusercontent.com/7327215/217473325-8152cd90-9b43-4dfe-bafa-4ce98b86f91d.png)

再次感谢分享！
