### ISSUE TITLE
reference的字体和行距较大

### ISSUE THREAD

**Issue by Guiliang** [Ruzim/NSFC-application-template-latex#4]
闫老师您好，

感谢您制作的模板！

我发现这个模板reference的字体和行距都较大（红色箭头），引用占的页数总比MS模板多，不知能有没有啥办法压缩一下呀？
<img width="451" alt="Screen Shot 2023-02-11 at 11 54 42" src="https://user-images.githubusercontent.com/22108101/218237961-bcf7b2f8-5fa3-44b0-9891-248faa60c87a.png">

我研究了半天“ieeetrNSFC.bst”这个文件，也没弄明白要怎么修改

期待您的回复

**Comment by Ruzim** [comment]
改bst貌似没用，https://texfaq.org/FAQ-compactbib 这上面说的比较透彻。但我也不知道比较简单又不引起其他问题的改法。。。

**Comment by Guiliang** [comment]
感谢提供参考！
我发现加上
\usepackage[numbers]{natbib}
\setlength{\bibsep}{0.0pt}
似乎可以解决这个问题
