### ISSUE TITLE
section标题有部分没有加粗

### ISSUE THREAD

**Issue by Amo-Zeng** [Ruzim/NSFC-application-template-latex#5]
你好，我下载的青基模板，发现第一个subsection ”（一）立项依据与研究内容（建议8000字以内）：”中的”（建议8000字以内）：“是没加粗的，请问这个怎么解决。
另外我的xelatex 好像无法识别\kaishu和\kern，但是也没有看到它们的定义所在，请问是字体的问题吗?
另外我从系统下载的版本和模版有几处不一致：
”正在承担的与本项目相关的科研项目情况（申请人正在承担“、”具有高级专业技术职务（职称）的申请人是否存在同年申请“ 和”3. 具有高级专业技术职务（职称）的申请人是否存在“    
这三处是单独的”申请人“，而不是”申请人或者主要参与者“

**Comment by Ruzim** [comment]
正如说明中指出的，这是面上的模板。青年基金可以根据官方模板自行修改调整，改动不多。编译器推荐采用textlive，我在windows下编译没有发现问题。

**Comment by Amo-Zeng** [comment]
好的，谢谢
