### ISSUE TITLE
感觉在overleaf中正文的字体有些奇怪

### ISSUE THREAD

**Issue by williamzhao95** [Ruzim/NSFC-application-template-latex#7]
感觉在overleaf中正文的字体有些奇怪，是支持overleaf不太好吗，还是overleaf中文字体的问题

**Comment by Ruzim** [comment]
我没用过overleaf。。。还请用过overleaf的老师们解答。

**Comment by wine3603** [comment]
我再overleaf里显示找不到kaiti这个error，另外overleaf里的makeheld里面所有的数字和英文标点在各级标题里都消失了
