### ISSUE TITLE
在figure环境中插入图片后，图片与下一段文字之间出现间隔过大的情况

### ISSUE THREAD

**Issue by williamzhao95** [Ruzim/NSFC-application-template-latex#8]
在figure环境中插入图片后，图片与下一段文字之间出现间隔过大的情况，给的样例PDF也有类似情况

**Comment by Ruzim** [comment]
在认为需要缩短间距的地方加入 \vskip -2mm 看看效果

**Comment by TaihuLight** [comment]
\setlength{\intextsep}{6pt}   用这个命令也可以
